// Code generated by goctl. DO NOT EDIT.
// Source: {{template}}.proto

package {{template}}client

import (
	"context"

	"{{template}}/{{template}}"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = {{template}}.Request
	Response = {{template}}.Response

	{{Template}} interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	default{{template}} struct {
		cli zrpc.Client
	}
)

func New{{Template}}(cli zrpc.Client) {{template}} {
	return &default{{template}}{
		cli: cli,
	}
}

func (m *default{{template}}) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := {{template}}.New{{Template}}Client(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
